global:
  scrape_interval: 5s # Server 抓取頻率
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]
  - job_name: "node-exporter-localhost"
    static_configs:
      - targets: ["host.docker.internal:9100"]
  - job_name: "node-exporter-linux"
    static_configs:
      - targets: ["172.26.102.125:9100"]
  - job_name: "node-exporter-windows"
    static_configs:
      - targets: ["172.26.147.229:9182"]
  - job_name: "node-exporter-windows2"
    static_configs:
      - targets: ["172.26.5.148:9182"]

      # to do list: 研究是否可以觀看同一電腦下的不同槽，並可以自行選擇要看哪一個 disk; 
      # 並且研究要如何透過  docker 多台部署並輸入 ip (長遠研究)

  

