global:
  scrape_interval: 30s # Server 抓取頻率
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]
  
  - job_name: "CPU_K8S1_ALL"
    static_configs:
      - targets: ["172.20.254.101:9100"]
        labels:
            alias: 'K8S1_ALL'

  # 暫時先註解掉 特定路徑語法 job
  # - job_name: "CPU_K8S1_Specific"
  #   static_configs:
  #     - targets: ["172.20.254.101:9100"]
  #       labels:
  #         alias: 'K8S1_Specific'
  #   metric_relabel_configs:
  #     - source_labels: [__name__]
  #       regex: '(node_uname_info|node_cpu_.*|node_memory_.*|node_filesystem_.*)'
  #       action: keep

  #     - source_labels: [mountpoint]
  #       regex: '(^(/|/boot/efi)$|)'
  #       action: keep
  
    #LPR10-cpu
  - job_name: "CPU-Lpr10"
    static_configs:
      - targets: ["10.239.35.110:9100"]
        labels:
          alias: 'CPU LPR10'
  
  #LPR11-cpu
  - job_name: "CPU-Lpr11"
    static_configs:
      - targets: ["10.239.35.111:9100"]
        labels:
          alias: 'CPU LPR11'

  # #LPR12-cpu
  # - job_name: "CPU-Lpr12"
  #   static_configs:
  #     - targets: ["10.239.35.112:9100"]
  #       labels:
  #         alias: 'CPU LPR12'

  #LPR13-cpu
  - job_name: "CPU-Lpr13"
    static_configs:
      - targets: ["10.239.35.113:9100"]
        labels:
          alias: 'CPU LPR13'

  #LPR14-cpu
  - job_name: "CPU-Lpr14"
    static_configs:
      - targets: ["10.239.35.114:9100"]
        labels:
          alias: 'CPU LPR14'

  #LPR01-cpu
  - job_name: "CPU-Lpr01"
    static_configs:
      - targets: ["10.239.35.101:9100"]
        labels:
          alias: 'CPU LPR01'

  #LPR02-cpu
  - job_name: "CPU-Lpr02"
    static_configs:
      - targets: ["10.239.35.102:9100"]
        labels:
          alias: 'CPU LPR02'

  #LPR03-cpu
  - job_name: "CPU-Lpr03"
    static_configs:
      - targets: ["10.239.35.103:9100"]
        labels:
          alias: 'CPU LPR03'

  #LPR04-cpu
  - job_name: "CPU-Lpr04"
    static_configs:
      - targets: ["10.239.35.104:9100"]
        labels:
          alias: 'CPU LPR04'

  #LPR05-cpu
  - job_name: "CPU-Lpr05"
    static_configs:
      - targets: ["10.239.35.105:9100"]
        labels:
          alias: 'CPU LPR05'

  #LPR06-cpu
  - job_name: "CPU-Lpr06"
    static_configs:
      - targets: ["10.239.35.106:9100"]
        labels:
          alias: 'CPU LPR06'

  #LPR07-cpu
  - job_name: "CPU-Lpr07"
    static_configs:
      - targets: ["10.239.35.107:9100"]
        labels:
          alias: 'CPU LPR07'

  #LPR08-cpu
  - job_name: "CPU-Lpr08"
    static_configs:
      - targets: ["10.239.35.108:9100"]
        labels:
          alias: 'CPU LPR08'

  #LPR09-cpu
  - job_name: "CPU-Lpr09"
    static_configs:
      - targets: ["10.239.35.109:9100"]
        labels:
          alias: 'CPU LPR09'

  #ttydb1-cpu
  - job_name: "CPU-ttydb1"
    static_configs:
      - targets: ["10.239.35.11:9100"]
        labels:
          alias: 'CPU ttydb1'

  #ttydb2-cpu
  - job_name: "CPU-ttydb2"
    static_configs:
      - targets: ["10.239.35.12:9100"]
        labels:
          alias: 'CPU ttydb2'

  #ttydb3-cpu
  - job_name: "CPU-ttydb3"
    static_configs:
      - targets: ["10.239.35.13:9100"]
        labels:
          alias: 'CPU ttydb3' 


  #LPR15-cpu
  - job_name: "CPU-Lpr15"
    static_configs:
      - targets: ["10.239.35.115:9100"]
        labels:
          alias: 'CPU LPR15'

  #LPR16-cpu
  - job_name: "CPU-Lpr16"
    static_configs:
      - targets: ["10.239.35.116:9100"]
        labels:
          alias: 'CPU LPR16'

  #LPR18-cpu
  - job_name: "CPU-Lpr18"
    static_configs:
      - targets: ["10.239.35.118:9100"]
        labels:
          alias: 'CPU LPR18'

#LPR19-cpu
  - job_name: "CPU-Lpr19"
    static_configs:
      - targets: ["10.239.35.119:9100"]
        labels:
          alias: 'CPU LPR19'
  #LPR20-cpu
  - job_name: "CPU-Lpr20"
    static_configs:
      - targets: ["10.239.35.120:9100"]
        labels:
          alias: 'CPU LPR20'
  #LPR21-cpu
  - job_name: "CPU-Lpr21"
    static_configs:
      - targets: ["10.239.35.121:9100"]
        labels:
          alias: 'CPU LPR21'
  #LPR22-cpu
  - job_name: "CPU-Lpr22"
    static_configs:
      - targets: ["10.239.35.122:9100"]
        labels:
          alias: 'CPU LPR22'
  #LPR23-cpu
  - job_name: "CPU-Lpr23"
    static_configs:
      - targets: ["10.239.35.123:9100"]
        labels:
          alias: 'CPU LPR23'
  #LPR24-cpu
  - job_name: "CPU-Lpr24"
    static_configs:
      - targets: ["10.239.35.124:9100"]
        labels:
          alias: 'CPU LPR24'
  #LPR25-cpu
  - job_name: "CPU-Lpr25"
    static_configs:
      - targets: ["10.239.35.125:9100"]
        labels:
          alias: 'CPU LPR25'
  #LPR26-cpu
  - job_name: "CPU-Lpr26"
    static_configs:
      - targets: ["10.239.35.126:9100"]
        labels:
          alias: 'CPU LPR26'
  #LPR27-cpu
  - job_name: "CPU-Lpr27"
    static_configs:
      - targets: ["10.239.35.127:9100"]
        labels:
          alias: 'CPU LPR27'
  #LPR28-cpu
  - job_name: "CPU-Lpr28"
    static_configs:
      - targets: ["10.239.35.128:9100"]
        labels:
          alias: 'CPU LPR28'
  #LPR29-cpu
  - job_name: "CPU-Lpr29"
    static_configs:
      - targets: ["10.239.35.129:9100"]
        labels:
          alias: 'CPU LPR29'
#-------------------------------------
  #LPR01-gpu
  - job_name: "dcgm-exporter-lpr01"
    static_configs:
      - targets: ["10.239.35.101:9400"]
        labels:
          alias: 'GPU LPR01'

  #LPR02-gpu
  - job_name: "dcgm-exporter-lpr02"
    static_configs:
      - targets: ["10.239.35.102:9400"]
        labels:
          alias: 'GPU LPR02'

  #LPR03-gpu
  - job_name: "dcgm-exporter-lpr03"
    static_configs:
      - targets: ["10.239.35.103:9400"]
        labels:
          alias: 'GPU LPR03'

  #LPR04-gpu
  - job_name: "dcgm-exporter-lpr04"
    static_configs:
      - targets: ["10.239.35.104:9400"]
        labels:
          alias: 'GPU LPR04'

  #LPR05-gpu
  - job_name: "dcgm-exporter-lpr05"
    static_configs:
      - targets: ["10.239.35.105:9400"]
        labels:
          alias: 'GPU LPR05'

  #LPR06-gpu
  - job_name: "dcgm-exporter-lpr06"
    static_configs:
      - targets: ["10.239.35.106:9400"]
        labels:
          alias: 'GPU LPR06'

  #LPR07-gpu
  - job_name: "dcgm-exporter-lpr07"
    static_configs:
      - targets: ["10.239.35.107:9400"]
        labels:
          alias: 'GPU LPR07'

  #LPR08-gpu
  - job_name: "dcgm-exporter-lpr08"
    static_configs:
      - targets: ["10.239.35.108:9400"]
        labels:
          alias: 'GPU LPR08'

  #LPR09-gpu
  - job_name: "dcgm-exporter-lpr09"
    static_configs:
      - targets: ["10.239.35.109:9400"]
        labels:
          alias: 'GPU LPR09'

  #LPR10-gpu
  - job_name: "dcgm-exporter-lpr10"
    static_configs:
      - targets: ["10.239.35.110:9400"]
        labels:
          alias: 'GPU LPR10'

  #LPR11-gpu
  - job_name: "dcgm-exporter-lpr11"
    static_configs:
      - targets: ["10.239.35.111:9400"]
        labels:
          alias: 'GPU LPR11'

  # #LPR12-gpu
  # - job_name: "dcgm-exporter-lpr12"
  #   static_configs:
  #     - targets: ["10.239.35.112:9400"]
  #       labels:
  #         alias: 'GPU LPR12'
  
  #LPR13-gpu
  - job_name: "dcgm-exporter-lpr13"
    static_configs:
      - targets: ["10.239.35.113:9400"]
        labels:
          alias: 'GPU LPR13'

  #LPR14-gpu
  - job_name: "dcgm-exporter-lpr14"
    static_configs:
      - targets: ["10.239.35.114:9400"]
        labels:
          alias: 'GPU LPR14'

  #LPR15-gpu
  - job_name: "dcgm-exporter-lpr15"
    static_configs:
      - targets: ["10.239.35.115:9400"]
        labels:
          alias: 'GPU LPR15'

  #LPR16-gpu
  - job_name: "dcgm-exporter-lpr16"
    static_configs:
      - targets: ["10.239.35.116:9400"]
        labels:
          alias: 'GPU LPR16'

  #LPR18-gpu
  - job_name: "dcgm-exporter-lpr18"
    static_configs:
      - targets: ["10.239.35.118:9400"]
        labels:
          alias: 'GPU LPR18'

  #LPR19-gpu
  - job_name: "dcgm-exporter-lpr19"
    static_configs:
      - targets: ["10.239.35.119:9400"]
        labels:
          alias: 'GPU LPR19'

#LPR20-gpu
  - job_name: "dcgm-exporter-lpr20"
    static_configs:
      - targets: ["10.239.35.120:9400"]
        labels:
          alias: 'GPU LPR20'
  #LPR21-gpu
  - job_name: "dcgm-exporter-lpr21"
    static_configs:
      - targets: ["10.239.35.121:9400"]
        labels:
          alias: 'GPU LPR21'
  #LPR22-gpu
  - job_name: "dcgm-exporter-lpr22"
    static_configs:
      - targets: ["10.239.35.122:9400"]
        labels:
          alias: 'GPU LPR22'
  #LPR23-gpu
  - job_name: "dcgm-exporter-lpr23"
    static_configs:
      - targets: ["10.239.35.123:9400"]
        labels:
          alias: 'GPU LPR23'
  #LPR24-gpu
  - job_name: "dcgm-exporter-lpr24"
    static_configs:
      - targets: ["10.239.35.124:9400"]
        labels:
          alias: 'GPU LPR24'
  #LPR25-gpu
  - job_name: "dcgm-exporter-lpr25"
    static_configs:
      - targets: ["10.239.35.125:9400"]
        labels:
          alias: 'GPU LPR25'
  #LPR26-gpu
  - job_name: "dcgm-exporter-lpr26"
    static_configs:
      - targets: ["10.239.35.126:9400"]
        labels:
          alias: 'GPU LPR26'
  #LPR27-gpu
  - job_name: "dcgm-exporter-lpr27"
    static_configs:
      - targets: ["10.239.35.127:9400"]
        labels:
          alias: 'GPU LPR27'
  #LPR28-gpu
  - job_name: "dcgm-exporter-lpr28"
    static_configs:
      - targets: ["10.239.35.128:9400"]
        labels:
          alias: 'GPU LPR28'
  #LPR29-gpu
  - job_name: "dcgm-exporter-lpr29"
    static_configs:
      - targets: ["10.239.35.129:9400"]
        labels:
          alias: 'GPU LPR29'
#------- LPR APP 8080 & 8081 Ports Monitoring -------
  - job_name: 'lpr-app-8080'
    static_configs:
      - targets:
          - '31.114.254.51'
          - '31.114.254.52'
          - '31.114.254.53'
          - '31.114.254.54'
          - '31.114.254.55'
          - '31.114.254.56'
          - '31.114.254.57'
          - '31.114.254.58'
          - '31.114.254.59'
          - '31.114.254.60'
          - '31.114.254.61'
          - '31.114.254.62'
          - '31.114.254.63'
          - '31.114.254.64'
          - '31.114.254.65'
          - '31.114.254.66'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: '${1}:8080' # 將讀取到的 IP (${1}) 加上 ":8080"

  # Job 2: 專門監控所有主機的 8081 Port
  - job_name: 'lpr-app-8081'
    static_configs:
      - targets:
          - '31.114.254.51'
          - '31.114.254.52'
          - '31.114.254.53'
          - '31.114.254.54'
          - '31.114.254.55'
          - '31.114.254.56'
          - '31.114.254.57'
          - '31.114.254.58'
          - '31.114.254.59'
          - '31.114.254.60'
          - '31.114.254.61'
          - '31.114.254.62'
          - '31.114.254.63'
          - '31.114.254.64'
          - '31.114.254.65'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: '${1}:8081' # 將讀取到的 IP (${1}) 加上 ":8081"