global:
  scrape_interval: 5s # Server 抓取頻率
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]
  - job_name: "node-exporter-localhost"
    static_configs:
      - targets: ["host.docker.internal:9100"]
  - job_name: "node-exporter-linux"
    static_configs:
      - targets: ["172.26.102.125:9100"]

